### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by JamiKettunen** [sailfishos-oneplus5/hybris-installer#1]
- [ ] [Figure out a way to trim the backed up droid-boot.img (64 MB => ~19 MB)](https://git.io/fjyBT)
- [ ] Shorten displayed version to e.g. `3.2.0` vs `3.2.0.12`
- [ ] Improve support for A/B devices
- [ ] Update adaptation guide lines to match latest commit
- [ ] Mask `vendor-*.mount` systemd units when not using LineageOS as a base(?)
- [x] Implement [AnyKernel3](https://github.com/osm0sis/AnyKernel3) by @osm0sis to reduce zip size further & make flashing process faster
- [x] Start using SFOS' `/boot/hybris-boot.img` instead of the one from zip!
- [x] Don't copy `hybris-*` script files at all in `sfe-*` build out directories (they are useless & ignored)
